version: '3'

networks:
  consul-network:
    driver: bridge
    ipam:
     config:
      - subnet: 172.20.1.0/24

services:
  nats:
    networks: 
      - consul-network
    container_name: nats
    image: "nats"
    restart: always
  mongo:
    networks: 
      - consul-network
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  frontend:
    networks: 
      - consul-network
    container_name: "frontend"
    build: "./frontend"
    restart: always
    ports:
      - "8080:8080"
    links: 
      - rest-api
      - ws-server
  data-consumer:
    networks: 
      - consul-network
    container_name: "data-consumer"
    build: "./data-consumer"
    restart: always
    environment: 
      - NATS_URL=nats://nats:4222
      - MONGO_DSN=mongodb://mongo:27017/statistics
    links: 
      - nats
      - mongo
  vehicle-data-generator:
    networks: 
      - consul-network
    container_name: "vehicle-data-generator"
    build: "./vehicle-data-generator"
    restart: always
    environment: 
      - NATS_URL=nats://nats:4222
    links: 
      - nats
  incident-reporter:
    networks: 
      - consul-network
    container_name: "incident-reporter"
    build: "./incident-reporter"
    restart: always
    environment: 
      - NATS_URL=nats://nats:4222
      - MONGO_DSN=mongodb://mongo:27017/incidents
    links: 
      - nats
      - mongo
  rest-api:
    networks: 
      - consul-network
    container_name: "rest-api"
    build: "./rest-api"
    restart: always
    environment:
      - MONGO_DSN=mongodb://mongo:27017/statistics
    ports:
      - "3000:3000"
    depends_on: 
      - nats
      - mongo
  ws-server:
    networks: 
      - consul-network
    container_name: "ws-server"
    build: "./ws-server"
    restart: always
    ports:
      - "8000:8000"
    environment: 
      - NATS_URL=nats://nats:4222
    depends_on: 
      - nats
  # consul-server:
  #   container_name: consul-server
  #   environment: 
  #     CONSUL_ALLOW_PRIVILEGED_PORTS: ""
  #   build: ./consul
  #   command: ["agent", "-ui", "-server", "-bootstrap=1", "-advertise=172.20.1.11", "-dns-port=53"] #  "-node=server-1",  ,, 
  #   ports:
  #     - "8500:8500"
  #     - "8600:8600/udp"
  #   networks:
  #     consul-network:
  #       ipv4_address: 172.20.1.11