version: '3'

networks:
  consul-network:
    driver: bridge
    ipam:
     config:
      - subnet: 172.20.1.0/24

services:
  # consul-server:
  #   container_name: consul-server
  #   environment: 
  #     CONSUL_ALLOW_PRIVILEGED_PORTS: ""
  #   build: ./consul
  #   command: ["agent", "-ui", "-server", "-bootstrap=1", "-advertise=172.20.1.11", "-dns-port=53"] #  "-node=server-1",  ,, 
  #   ports:
  #     - "8500:8500"
  #     - "8600:8600/udp"
  #   networks:
  #     consul-network:
  #       ipv4_address: 172.20.1.11
  nats:
    networks: 
      - consul-network
    container_name: nats
    image: "nats"
    ports:
      - "4222:4222"
  mongo:
    networks: 
      - consul-network
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  data-consumer:
    networks: 
      - consul-network
    container_name: "data-consumer"
    build: "./data-consumer"
    links: 
      - nats
      - mongo
  vehicle-data-generator:
    networks: 
      - consul-network
    container_name: "vehicle-data-generator"
    build: "./vehicle-data-generator"
    links: 
      - nats
  incident-reporter:
    networks: 
      - consul-network
    container_name: "incident-reporter"
    build: "./incident-reporter"
    links: 
      - nats
      - mongo
  rest-api:
    networks: 
      - consul-network
    container_name: "rest-api"
    build: "./rest-api"
    ports:
      - "3000:3000"
    depends_on: 
      - nats
      - mongo